catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade
packages:
  - packages/*
  - apps/*
overrides:
  vite: npm:rolldown-vite@latest

catalogs:
  dev-tools:
    '@antfu/eslint-config': ^6.7.3
    '@types/node': ^24.10.9
    '@typescript/native-preview': latest
    eslint: ^9.39.2
    tsdown: ^0.17.2
    tsx: ^4.21.0
    typescript: ^5.9.3
  git-tools:
    '@commitlint/cli': ^20.3.1
    '@commitlint/config-conventional': ^20.3.1
    commitlint: ^20.3.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  logger-family:
    '@types/express': ^5.0.6
    cls-rtracer: ^2.6.3
    nestjs-pino: ^4.5.0
    pino: ^10.3.0
    pino-http: ^11.0.0
    pino-pretty: ^13.1.3
    pino-roll: ^4.0.0
  nest-family:
    '@nestjs/common': ^11.1.12
    '@nestjs/core': ^11.1.12
    '@nestjs/jwt': ^11.0.2
    '@nestjs/passport': ^11.0.5
    '@nestjs/platform-express': ^11.1.12
    '@nestjs/testing': ^11.1.12
    '@types/cookie-parser': ^1.4.10
    '@types/ioredis': ^5.0.0
    '@types/jsonwebtoken': ^9.0.10
    '@types/passport-jwt': ^4.0.1
    cookie-parser: ^1.4.7
    dotenv: ^17.2.3
    drizzle-kit: ^0.31.8
    drizzle-orm: ^0.45.1
    ioredis: ^5.9.2
    jsonwebtoken: ^9.0.3
    nanoid: ^5.1.6
    passport: ^0.7.0
    passport-jwt: ^4.0.1
    pm2: ^6.0.14
    postgres: ^3.4.8
    reflect-metadata: ^0.2.2
    rxjs: ^7.8.2
    tssrp6a: ^3.0.0
    zod: ^4.3.6
  test-family:
    '@vitest/coverage-v8': ^4.0.18
    jsdom: ^27.4.0
  unocss-family:
    '@iconify-json/ion': ^1.2.3
    '@iconify-json/material-symbols': ^1.2.53
    '@iconify-json/simple-icons': ^1.2.68
    '@iconify-json/svg-spinners': ^1.2.3
    '@unocss/preset-uno': ^66.6.0
    '@unocss/preset-wind4': ^66.6.0
    '@unocss/vite': ^66.6.0
    unocss: ^66.6.0
  vite-family:
    '@vitejs/plugin-vue': ^6.0.3
    vite: ^7.3.1
    vite-plugin-inspect: ^11.3.3
    vitest: ^4.0.18
  vue-family:
    '@pinia/colada': ^0.21.2
    '@tanstack/vue-virtual': ^3.13.18
    '@vue/test-utils': ^2.4.6
    '@vue/tsconfig': ^0.8.1
    '@vueuse/core': ^14.1.0
    pinia: ^3.0.4
    vue: ^3.5.27
    vue-i18n: ^11.2.8
    vue-router: ^4.6.4
    vue-tsc: ^3.2.4
onlyBuiltDependencies:
  - '@nestjs/core'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
